"""Initial migration

Revision ID: acc663edf845
Revises: 
Create Date: 2025-04-15 22:47:15.190701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acc663edf845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_alertid', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_users_userid', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_games_appid', table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('appid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('appid', name='games_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_games_appid', 'games', ['appid'], unique=False)
    op.create_table('users',
    sa.Column('userid', sa.INTEGER(), server_default=sa.text("nextval('users_userid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('userid', name='users_pkey'),
    sa.UniqueConstraint('login', name='users_login_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_userid', 'users', ['userid'], unique=False)
    op.create_table('alerts',
    sa.Column('alertid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.MONEY(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appid'], ['games.appid'], name='alerts_appid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], name='alerts_userid_fkey'),
    sa.PrimaryKeyConstraint('alertid', name='alerts_pkey')
    )
    op.create_index('ix_alerts_alertid', 'alerts', ['alertid'], unique=False)
    # ### end Alembic commands ###
